name: github-action-test
on:
    pull_request:
        branches:
            - main
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone repository
              uses: actions/checkout@v2
            # ----------------------------
            - name: Install Node.js v16
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
            # ----------------------------
            - name: Install dependencies
              run: npm ci
            # ----------------------------
            - name: Run Test Suites
              run: npm run test
